version: "3"

services: 

    api:
        build: .
        command: ["yarn", "start"]
        env_file: 
            - config.env
        ports: 
            - "3000:3000"
        depends_on: 
            - mongo
            
    mongo:
        image: mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/prayNmeet
        volumes: 
            - prayNmeet:/data/db
        ports: 
            - "27017:27017"

volumes: 
    prayNmeet:  
    